# Generated by Django 2.0.4 on 2018-10-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HisData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Light_intensity', models.DecimalField(decimal_places=13, max_digits=15, verbose_name='光照强度（单位lux）')),
                ('Air_temperature', models.DecimalField(decimal_places=13, max_digits=15, verbose_name='空气温度//℃')),
                ('Air_humidity', models.DecimalField(decimal_places=13, max_digits=15, verbose_name='空气湿度//℃')),
                ('Soil_moisture', models.DecimalField(decimal_places=13, max_digits=15, verbose_name='土壤水分//℃')),
                ('Soil_temperature', models.DecimalField(decimal_places=13, max_digits=15, verbose_name='土壤温度//℃')),
                ('Time', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '数据',
                'verbose_name_plural': '数据',
            },
        ),
    ]
