# Generated by Django 2.0.4 on 2018-11-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0003_plantdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataKind', models.CharField(max_length=32, verbose_name='数据类型')),
                ('HuanmiaoTimeH', models.DateField(verbose_name='缓苗期高')),
                ('HuanmiaoTimeL', models.DateField(verbose_name='缓苗期低')),
                ('ShenmanTimeH', models.DateField(verbose_name='伸蔓期高')),
                ('ShenmanTimeL', models.DateField(verbose_name='伸蔓期低')),
                ('ZuoguoTimeH', models.DateField(verbose_name='坐果期高')),
                ('ZuoguoTimeL', models.DateField(verbose_name='坐果期低')),
                ('PengguaTimeH', models.DateField(verbose_name='澎瓜期高')),
                ('PengguaTimeL', models.DateField(verbose_name='澎瓜期低')),
                ('ChengshuTimeH', models.DateField(verbose_name='成熟期高')),
                ('ChengshuTimeL', models.DateField(verbose_name='成熟期低')),
            ],
            options={
                'verbose_name_plural': '数据类型',
                'verbose_name': '数据类型',
            },
        ),
    ]
